---
- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items: "{{ rpms_common }}"

- name: COMMON | Disable SELinux
  selinux:
    state: disabled

- name: COMMON | Update /etc/hosts from inventory
  lineinfile:
    dest=/etc/hosts
    line={{ item }} state=present
  with_items: "{{ hostfile }}"

- name: COMMON | Disable Firewall
  systemd:
    name=firewalld enabled=no
    name=firewalld state=stopped
  ignore_errors: yes




